### ISSUE TITLE
Sync is off 4 hrs

### ISSUE THREAD

**Issue by Alchemjst** [francoisfaubert/starcraft-calendar#1]
Right now in NY and all the events are 4 hours too early.
So it will state that the event starts in 31 minutes (12 am 7/24/14) on http://wcs.battle.net/sc2/en/schedule but my calendar says 8-9 pm (7/23/14).

**Comment by francoisfaubert** [comment]
I have missed the notification, really sorry for the delay in answering you :s

I will see if I can save the time in UTC so that the event times are universal. At the moment, the display time is the server's. I'll try to have something by this afternoon.

**Comment by francoisfaubert** [comment]
I have added the timezone parameter to the generated ical file. It should help enforce the formatting of local times.
